apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-ptp
placementRef:
  name: placement-policy-ptp
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-ptp-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
