apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-du-rt-kernel-policy
  namespace: profile-ran-subscriptions
placementRef:
  name: placement-policy-du-rt-kernel-policy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-config-rt-kernel-du
  kind: Policy
  apiGroup: policy.open-cluster-management.io
