apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-sample-site-du-sriov-network-node-policy
  namespace: sample-site-du-subscription
spec:
  clusterConditions:
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["sample-du-cluster"]}
