apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-sample-site-cu-sriov-nnode-policy
  namespace: sample-site-cu-subscription
spec:
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["sample-site-cu-cluster"]}
