apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-mcp-du
  namespace: du-subscriptions
spec:
  clusterConditions:
  clusterSelector:
    matchExpressions:
      - {key: profile, operator: In, values: [du]}
