apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00_mcp_cu_policy.yaml
  - 01_mcp_cu_placementbinding.yaml
  - 02_mcp_cu_placementrule.yaml
  - 03_sriov_operator_config_policy.yaml
  - 04_sriov_operator_config_policy_placementbinding.yaml
  - 05_sriov_operator_config_policy_placementrule.yaml
  - 06_performance_profile_policy.yaml
  - 07_performance_profile_placementbinding.yaml
  - 08_performance_profile_placementrule.yaml
  - 0900_ptp_operator_policy.yaml
  - 0901_ptp_operator_placementbinding.yaml
  - 0902_ptp_operator_placementrule.yaml
  - 09_slave_ptp_policy.yaml
  - 10_slave_ptp_placementbinding.yaml
  - 11_slave_ptp_placementrule.yaml
  - 12_sctp_module_policy.yaml
  - 13_sctp_module_placementbinding.yaml
  - 14_sctp_module_placementrule.yaml
  - 15_rt_kernel_hack.yaml
  - 16_rt_kernel_placementbinding.yaml
  - 17_rt_kernel_placementrule.yaml
  - 18_disable_chronyd_policy.yaml
  - 19_disable_chronyd_placementbinding.yaml
  - 20_disable_chronyd_placementrule.yaml
