apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-sample-site-du-sriov-network
  namespace: sample-site-du-subscription
spec:
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["sample-site-du-cluster"]}
