apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-config-slave-ptp-du
  namespace: sites-ran-subscriptions
spec:
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["sample-site-du-cluster"]}
